# Generated by Django 5.1.7 on 2026-06-15 13:26

from django.db import migrations, models


def mark_existing_incidents_active(apps, schema_editor):
    Alert = apps.get_model("core", "Alert")
    Alert.objects.filter(
        type__in=["GPS_DECONNECTE", "SORTIE_ZONE"],
        is_read=False,
    ).update(incident_actif=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alert_driver_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='incident_actif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livreur',
            name='contrat',
            field=models.FileField(blank=True, null=True, upload_to='contrats/'),
        ),
        migrations.AddField(
            model_name='livreur',
            name='date_debut_contrat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='date_fin_contrat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='type_contrat',
            field=models.CharField(choices=[('CDD', 'CDD'), ('CDI', 'CDI')], default='CDI', max_length=3),
        ),
        migrations.RunPython(mark_existing_incidents_active, migrations.RunPython.noop),
    ]
