# Generated by Django 5.1.7 on 2026-06-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alert_incident_actif_livreur_contrat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
