# Generated by Django 5.1.7 on 2026-06-19 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alert_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(80)]),
        ),
    ]
